#!/bin/bash
TARGETS="/etc/pinger/targets.csv"
while true
do
while read line
do
	IP=$(echo $line | cut -d ',' -f1)
	NAME=$(echo $line | cut -d ',' -f2)
	CURRENT=$(ps aux | grep  "pinger $IP $NAME" | wc -l)
	if [ $CURRENT -lt 2 ];then
		nohup pinger $IP $NAME & &>/dev/null
	fi
done < $TARGETS
	sleep 600
done
